### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by aaronang**
Updated README with some "useful" information.

### CODE REVIEW

**Comment by ValMai** [comment]
Nice simple description. Do we welcome other people to join or not? We never know what can happen, and if we keep this project up for 10 weeks it might attract some attention? We can just leave it like this, then I'll merge.

**Comment by aaronang** [comment]
I do not expect other people to join and I won't give them direct write access. So they will need to create a fork. 

We ca  edit the README such that it is clear that people shouldn't contribute for now?

**Comment by ValMai** [comment]
Yes. Add something like:
"The purpose of this project is purely educational. It is meant for the use of our project group only."
What do you think?

**Comment by aaronang** [comment]
@ValMai Added your proposal. 

@basvijzendoorn @vliegenthart @ValMai Note that `*.rdoc` syntax is silghtly different from the standard Markdown syntax. Refer to http://jan.varwig.org/wp-content/uploads/2006/09/Rdoc%20Cheat%20Sheet.pdf for the syntax.

**Comment by ValMai** [comment]
If you agree, I'll merge

**Comment by aaronang** [comment]
@ValMai :+1:

**Pull request merged**
